language: cpp
os:
- linux
dist: bionic
addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - libeigen3-dev
      - python-numpy
script:
  mkdir build && cd build && cmake .. && make && make test
